# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/freelancer_os
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8081

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=freelanceros.mailer@gmail.com
spring.mail.password=advhqcznokhenxlr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true